"""Closed contract for staging-only conditional-coupon shadow observation fixture harness."""
from __future__ import annotations

FIXTURE_SCHEMA_VERSION = "coupon_shadow_fixture_v1"

CONFIRMATION_TOKEN_WRITE = "RUN_COUPON_SHADOW_FIXTURE_WRITE"
CONFIRMATION_ENV_WRITE = "NAHLA_COUPON_SHADOW_FIXTURE_WRITE_CONFIRM"

CONFIRMATION_TOKEN_CLEANUP = "RUN_COUPON_SHADOW_FIXTURE_CLEANUP"
CONFIRMATION_ENV_CLEANUP = "NAHLA_COUPON_SHADOW_FIXTURE_CLEANUP_CONFIRM"

REQUIRED_ALEMBIC_REVISIONS = frozenset({"0088", "0089"})

CAPABILITY_KEY = "order_customer_identity"
CAPABILITY_STATE_VALIDATED = "validated"
VALIDATION_REVISION_0088 = "0088"

STAGING_PROJECT_ENV = "RAILWAY_PROJECT_NAME"
STAGING_ENVIRONMENT_ENV = "RAILWAY_ENVIRONMENT_NAME"
STAGING_PROJECT_VALUE = "desirable-growth"
STAGING_ENVIRONMENT_VALUE = "staging"
STAGING_IDENTITY_CLASS = "railway_staging_desirable_growth"

# Isolated deterministic namespace — never overlaps production rows.
FIXTURE_NAMESPACE = "cc_shadow_g4_generic_v1"
FIXTURE_MARKER_FIELD = "coupon_shadow_fixture_namespace"
FIXTURE_SLOT_FIELD = "coupon_shadow_fixture_slot"
FIXTURE_EXTERNAL_ID_PREFIX = "CCS4FX"

# Bounded fixture shape (strict caps; no batch growth).
MAX_INTERNAL_CUSTOMERS = 1
MAX_CONVERSATIONS = 1
MAX_COUNTABLE_ORDERS = 2
MAX_CONDITIONAL_PROMOTIONS = 1
MIN_ORDERS_THRESHOLD = 2
MIN_COUNTABLE_ORDERS = 2

FIXTURE_SLOT_INTERNAL_CUSTOMER = "internal_customer"
FIXTURE_SLOT_CONVERSATION = "conversation"
FIXTURE_SLOT_COUNTABLE_ORDER = "countable_order"
FIXTURE_SLOT_CONDITIONAL_PROMOTION = "conditional_promotion"

FIXTURE_CONVERSATION_SUFFIX = "CONV"
FIXTURE_COUNTABLE_ORDER_SUFFIX = "ORD"

# Generic commerce deterministic labels (not emitted in operator JSON).
GENERIC_MERCHANT_NAME = "متجر تجريبي عام"
GENERIC_INTERNAL_CUSTOMER_NAME = "أحمد سالم"
GENERIC_PRODUCT_SHOES = "حذاء رياضي أبيض"
GENERIC_CITY = "الرياض"
GENERIC_SHORT_CODE = "RRRD1234"

# Test-only loader probe — never set by the operator harness in staging.
TEST_LOADER_PROBE_ENV = "NAHLA_COUPON_SHADOW_FIXTURE_LOADER_PROBE"

__all__ = [
    "CAPABILITY_KEY",
    "CAPABILITY_STATE_VALIDATED",
    "CONFIRMATION_ENV_CLEANUP",
    "CONFIRMATION_ENV_WRITE",
    "CONFIRMATION_TOKEN_CLEANUP",
    "CONFIRMATION_TOKEN_WRITE",
    "FIXTURE_CONVERSATION_SUFFIX",
    "FIXTURE_COUNTABLE_ORDER_SUFFIX",
    "FIXTURE_EXTERNAL_ID_PREFIX",
    "FIXTURE_MARKER_FIELD",
    "FIXTURE_NAMESPACE",
    "FIXTURE_SCHEMA_VERSION",
    "FIXTURE_SLOT_CONDITIONAL_PROMOTION",
    "FIXTURE_SLOT_CONVERSATION",
    "FIXTURE_SLOT_COUNTABLE_ORDER",
    "FIXTURE_SLOT_FIELD",
    "FIXTURE_SLOT_INTERNAL_CUSTOMER",
    "GENERIC_CITY",
    "GENERIC_INTERNAL_CUSTOMER_NAME",
    "GENERIC_MERCHANT_NAME",
    "GENERIC_PRODUCT_SHOES",
    "GENERIC_SHORT_CODE",
    "MAX_CONDITIONAL_PROMOTIONS",
    "MAX_CONVERSATIONS",
    "MAX_COUNTABLE_ORDERS",
    "MAX_INTERNAL_CUSTOMERS",
    "MIN_COUNTABLE_ORDERS",
    "MIN_ORDERS_THRESHOLD",
    "REQUIRED_ALEMBIC_REVISIONS",
    "STAGING_ENVIRONMENT_ENV",
    "STAGING_ENVIRONMENT_VALUE",
    "STAGING_IDENTITY_CLASS",
    "STAGING_PROJECT_ENV",
    "STAGING_PROJECT_VALUE",
    "TEST_LOADER_PROBE_ENV",
    "VALIDATION_REVISION_0088",
]
