"""Closed contract for staging-only A1 generic-commerce evidence fixture harness."""
from __future__ import annotations

FIXTURE_SCHEMA_VERSION = "a1_evidence_fixture_v1"

CONFIRMATION_TOKEN_WRITE = "RUN_A1_EVIDENCE_FIXTURE_WRITE"
CONFIRMATION_ENV_WRITE = "NAHLA_A1_EVIDENCE_FIXTURE_WRITE_CONFIRM"

CONFIRMATION_TOKEN_CLEANUP = "RUN_A1_EVIDENCE_FIXTURE_CLEANUP"
CONFIRMATION_ENV_CLEANUP = "NAHLA_A1_EVIDENCE_FIXTURE_CLEANUP_CONFIRM"

REQUIRED_ALEMBIC_REVISION = "0087"

CAPABILITY_KEY = "order_customer_identity"
CAPABILITY_STATE_EXPAND = "expand"

STAGING_PROJECT_ENV = "RAILWAY_PROJECT_NAME"
STAGING_ENVIRONMENT_ENV = "RAILWAY_ENVIRONMENT_NAME"
STAGING_PROJECT_VALUE = "desirable-growth"
STAGING_ENVIRONMENT_VALUE = "staging"
STAGING_IDENTITY_CLASS = "railway_staging_desirable_growth"

# Isolated deterministic namespace — never overlaps production rows.
FIXTURE_NAMESPACE = "a1_g4_generic_commerce_v1"
FIXTURE_MARKER_KEY = "a1_evidence_fixture_namespace"
FIXTURE_SLOT_KEY = "a1_evidence_fixture_slot"
FIXTURE_EXTERNAL_ID_PREFIX = "A1G4FX"

# Bounded fixture shape (strict caps; no batch growth).
MAX_INTERNAL_ORDERS = 1
MAX_EXTERNAL_ORDERS = 1
MAX_INTERNAL_CUSTOMERS = 1
MAX_EXTERNAL_PROFILES = 1
MAX_INTEGRATIONS = 1

# Generic commerce deterministic labels (not emitted in operator JSON).
GENERIC_MERCHANT_NAME = "متجر تجريبي عام"
GENERIC_INTERNAL_CUSTOMER_NAME = "أحمد سالم"
GENERIC_EXTERNAL_CUSTOMER_NAME = "نورة عبدالله"
GENERIC_PRODUCT_SHOES = "حذاء رياضي أبيض"
GENERIC_PRODUCT_PERFUME = "عطر ورد 100ml"
GENERIC_CITY = "الرياض"
GENERIC_SHORT_CODE = "RRRD1234"

FIXTURE_SLOT_INTEGRATION = "integration"
FIXTURE_SLOT_INTERNAL_CUSTOMER = "internal_customer"
FIXTURE_SLOT_INTERNAL_ORDER = "internal_order"
FIXTURE_SLOT_EXTERNAL_ORDER = "external_order"

FIXTURE_EXTERNAL_STORE_SUFFIX = "STORE"
FIXTURE_EXTERNAL_CUSTOMER_REF = "EXT-CUST-01"
FIXTURE_INTERNAL_ORDER_SUFFIX = "INT-ORD-01"
FIXTURE_EXTERNAL_ORDER_SUFFIX = "EXT-ORD-01"

__all__ = [
    "CAPABILITY_KEY",
    "CAPABILITY_STATE_EXPAND",
    "CONFIRMATION_ENV_CLEANUP",
    "CONFIRMATION_ENV_WRITE",
    "CONFIRMATION_TOKEN_CLEANUP",
    "CONFIRMATION_TOKEN_WRITE",
    "FIXTURE_EXTERNAL_CUSTOMER_REF",
    "FIXTURE_EXTERNAL_ID_PREFIX",
    "FIXTURE_EXTERNAL_ORDER_SUFFIX",
    "FIXTURE_EXTERNAL_STORE_SUFFIX",
    "FIXTURE_INTERNAL_ORDER_SUFFIX",
    "FIXTURE_MARKER_KEY",
    "FIXTURE_NAMESPACE",
    "FIXTURE_SCHEMA_VERSION",
    "FIXTURE_SLOT_EXTERNAL_ORDER",
    "FIXTURE_SLOT_INTEGRATION",
    "FIXTURE_SLOT_INTERNAL_CUSTOMER",
    "FIXTURE_SLOT_INTERNAL_ORDER",
    "FIXTURE_SLOT_KEY",
    "GENERIC_CITY",
    "GENERIC_EXTERNAL_CUSTOMER_NAME",
    "GENERIC_INTERNAL_CUSTOMER_NAME",
    "GENERIC_MERCHANT_NAME",
    "GENERIC_PRODUCT_PERFUME",
    "GENERIC_PRODUCT_SHOES",
    "GENERIC_SHORT_CODE",
    "MAX_EXTERNAL_ORDERS",
    "MAX_EXTERNAL_PROFILES",
    "MAX_INTEGRATIONS",
    "MAX_INTERNAL_CUSTOMERS",
    "MAX_INTERNAL_ORDERS",
    "REQUIRED_ALEMBIC_REVISION",
    "STAGING_ENVIRONMENT_ENV",
    "STAGING_ENVIRONMENT_VALUE",
    "STAGING_IDENTITY_CLASS",
    "STAGING_PROJECT_ENV",
    "STAGING_PROJECT_VALUE",
]
