"""Closed contract for tenant-scoped A1 reconciliation write operator (post-0087 Expand)."""
from __future__ import annotations

WRITE_SCHEMA_VERSION = "a1_reconciliation_write_v1"

CONFIRMATION_TOKEN = "RUN_A1_RECONCILE_WRITE"
CONFIRMATION_ENV = "NAHLA_A1_RECONCILE_WRITE_CONFIRM"

DEFAULT_MAX_SUBJECTS_PER_KIND = 1_000
MAX_SUBJECTS_PER_KIND = 1_000

# This pre-0088 validation maintenance operator is pinned to Expand exactly.
REQUIRED_ALEMBIC_REVISION = "0087"

CAPABILITY_KEY = "order_customer_identity"
CAPABILITY_STATE_EXPAND = "expand"

STAGING_PROJECT_ENV = "RAILWAY_PROJECT_NAME"
STAGING_ENVIRONMENT_ENV = "RAILWAY_ENVIRONMENT_NAME"
STAGING_PROJECT_VALUE = "desirable-growth"
STAGING_ENVIRONMENT_VALUE = "staging"
STAGING_IDENTITY_CLASS = "railway_staging_desirable_growth"

__all__ = [
    "CAPABILITY_KEY",
    "CAPABILITY_STATE_EXPAND",
    "CONFIRMATION_ENV",
    "CONFIRMATION_TOKEN",
    "DEFAULT_MAX_SUBJECTS_PER_KIND",
    "MAX_SUBJECTS_PER_KIND",
    "STAGING_ENVIRONMENT_ENV",
    "STAGING_ENVIRONMENT_VALUE",
    "STAGING_IDENTITY_CLASS",
    "STAGING_PROJECT_ENV",
    "STAGING_PROJECT_VALUE",
    "REQUIRED_ALEMBIC_REVISION",
    "WRITE_SCHEMA_VERSION",
]
