"""
tests/test_catalog_focus_pin.py
───────────────────────────────
Locks the surgical-fix contract for **product-focus retention after a
WhatsApp catalog order** (June 2026).

Production reproducer
─────────────────────
The merchant captured a screenshot where a customer:

  1. Submitted a catalog order (a single item, SAR 69).
  2. Was asked for city + address by the bot (correct).
  3. Sent the national-address code and the city name.
  4. Bot then asked: "اختر المنتج اللي تبغاه من القائمة" — wrong, the
     product was already chosen via the catalog order.

Root cause: ``state.current_product_focus`` was never stamped from
the catalog payload, so the decision-engine gate at
``ACTION_STASH_ADDRESS_PRE_PRODUCT`` (which checks
``not state.current_product_focus``) treated the address turn as
"customer hasn't picked a product yet".

What this test file locks
─────────────────────────
1. ``_maybe_pin_catalog_focus`` only fires when the inbound text
   carries the canonical catalog-frame marker generated by
   ``modules.ai.media.normalizer`` — never on plain text.
2. The pin populates ``state.current_product_focus`` with stable
   keys (``id``, ``external_id``, ``title``, ``price``, ``currency``,
   ``from_catalog_order``).
3. When a focus already exists, the helper does **not** overwrite it.
4. Best-effort DB lookup: if the merchant's ``products`` table has
   a row whose ``external_id`` / ``sku`` / ``meta_retailer_id`` matches
   the SKU, the resolved title + numeric id are used. If not, a
   placeholder pin is still applied so the address-stash gate trips.
5. Decision-engine integration: with focus pinned (the post-catalog
   state), an inbound address signal does **not** route to
   ``ACTION_STASH_ADDRESS_PRE_PRODUCT``.
6. The pinning helper is wired into ``MerchantBrain.process`` before
   the decision engine runs (verified by source-grep so we don't
   import the heavy pipeline module at test time).

Constraints this fix obeys
──────────────────────────
* No new intents.
* No new outbound templates / canned replies.
* No new "checkout" layer.
* The brain still chooses the wording — we only flip a state flag
  the decision engine already understood.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, List
from unittest.mock import MagicMock

REPO_ROOT = Path(__file__).resolve().parents[1]
for p in [str(REPO_ROOT), str(REPO_ROOT / "backend"), str(REPO_ROOT / "database")]:
    if p not in sys.path:
        sys.path.insert(0, p)


# ── Helpers ──────────────────────────────────────────────────────────────

def _make_catalog_text(
    *,
    sku: str = "ext-69",
    qty: int = 1,
    total: float = 69.0,
    currency: str = "SAR",
    note: str | None = None,
) -> str:
    """Re-create the catalog-frame string the normalizer emits.

    Mirrors ``_process_catalog_order`` in ``modules/ai/media/normalizer.py``;
    we duplicate the shape here intentionally so any unintended drift in
    the marker / fields surfaces as a test failure rather than a silent
    mismatch in production.
    """
    lines: List[str] = ["[طلب كتالوج من العميل]"]
    lines.append(f"عدد المنتجات: {qty}")
    lines.append(f"الإجمالي: {total} {currency}")
    if sku:
        lines.append(f"رمز المنتج (SKU): {sku}")
    if note:
        lines.append(f"ملاحظة من العميل: {note}")
    lines.append("الرجاء معالجة هذا كنية شراء وإكمال الطلب.")
    return "\n".join(lines)


def _make_state(**overrides: Any):
    """Build a fresh ``MerchantConversationState`` with optional overrides."""
    from modules.ai.brain.types import MerchantConversationState
    state = MerchantConversationState()
    for k, v in overrides.items():
        setattr(state, k, v)
    return state


# ── 1. Marker / no-op gating ────────────────────────────────────────────

class TestCatalogFocusPinGating:
    def test_no_marker_does_not_pin(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        state = _make_state()
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1,
            message="السلام عليكم، أبغى عسل",
            state=state,
        )
        assert not state.current_product_focus

    def test_empty_message_does_not_raise(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        state = _make_state()
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1, message="", state=state,
        )
        assert not state.current_product_focus

    def test_none_message_does_not_raise(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        state = _make_state()
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1, message=None, state=state,
        )
        assert not state.current_product_focus

    def test_existing_focus_is_never_overwritten(self):
        """If the customer already picked a product through other paths
        (search → list → pick), the catalog frame must not clobber it."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        existing = {"id": 99, "external_id": "real-99", "title": "عسل سدر فاخر"}
        state = _make_state(current_product_focus=dict(existing))
        msg = _make_catalog_text(sku="other-sku")
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1, message=msg, state=state,
        )
        assert state.current_product_focus == existing


# ── 2. Field extraction ─────────────────────────────────────────────────

class TestCatalogFocusPinExtraction:
    def test_pins_with_db_resolution(self):
        """When the SKU matches a product row, prefer its title + id."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        product = MagicMock()
        product.id = 42
        product.title = "عسل سدر مع البروبوليس"
        product.price = 69.0

        # The pipeline calls ``db.query(Product).filter(...).filter(...).first()``.
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = product

        state = _make_state()
        msg = _make_catalog_text(sku="ext-69", qty=1, total=69.0, currency="SAR")
        _maybe_pin_catalog_focus(db=db, tenant_id=7, message=msg, state=state)

        f = state.current_product_focus
        assert f, "expected current_product_focus to be pinned"
        assert f["id"] == 42
        assert f["external_id"] == "ext-69"
        assert f["title"] == "عسل سدر مع البروبوليس"
        assert f["price"] == 69.0
        assert f["currency"] == "SAR"
        assert f["from_catalog_order"] is True

    def test_pins_placeholder_when_sku_unresolved(self):
        """Even when the SKU does not match any product row, we still
        stamp a placeholder focus — that's what gates the
        address-stash branch."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = None

        state = _make_state()
        msg = _make_catalog_text(sku="unknown-sku", qty=1, total=129.0, currency="SAR")
        _maybe_pin_catalog_focus(db=db, tenant_id=7, message=msg, state=state)

        f = state.current_product_focus
        assert f, "placeholder focus must be stamped even when DB lookup misses"
        assert f["external_id"] == "unknown-sku"
        assert f["from_catalog_order"] is True
        # Title falls back to empty so the LLM speaks naturally from
        # context (price / quantity) instead of echoing a fake title.
        assert f["title"] == ""
        assert f["price"] == 129.0
        assert f["currency"] == "SAR"

    def test_pins_when_db_lookup_raises(self):
        """A flaky DB / missing model must not break the pin."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.side_effect = RuntimeError("simulated outage")
        state = _make_state()
        msg = _make_catalog_text(sku="ext-99")
        _maybe_pin_catalog_focus(db=db, tenant_id=1, message=msg, state=state)
        f = state.current_product_focus
        assert f and f["external_id"] == "ext-99"
        assert f["from_catalog_order"] is True

    def test_unit_price_from_total_and_quantity(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = None
        state = _make_state()
        msg = _make_catalog_text(sku="multi", qty=3, total=180.0, currency="SAR")
        _maybe_pin_catalog_focus(db=db, tenant_id=1, message=msg, state=state)
        assert state.current_product_focus["price"] == 60.0  # 180 / 3

    def test_handles_message_with_no_sku(self):
        """Edge case: catalog frame missing SKU line still pins."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = None
        state = _make_state()
        # Skip the SKU line entirely.
        msg = "[طلب كتالوج من العميل]\nعدد المنتجات: 1\nالإجمالي: 50 SAR\n"
        _maybe_pin_catalog_focus(db=db, tenant_id=1, message=msg, state=state)
        f = state.current_product_focus
        assert f, "focus must still be pinned without an SKU"
        assert f["external_id"] == ""
        assert f["id"] == "catalog_order"
        assert f["from_catalog_order"] is True


# ── 3. Decision-engine integration ──────────────────────────────────────

class TestPostCatalogAddressDoesNotStash:
    """
    With ``current_product_focus`` pinned (the post-catalog state),
    an inbound address signal must NOT route to
    ``ACTION_STASH_ADDRESS_PRE_PRODUCT``.
    """

    def _build_ctx(self, *, focus, message, slots):
        from modules.ai.brain.types import (
            BrainContext,
            CommerceFacts,
            Intent,
            INTENT_GENERAL,
        )
        intent = Intent(
            name=INTENT_GENERAL,
            confidence=0.9,
            raw_message=message,
            slots=dict(slots),
        )
        state = _make_state()
        if focus:
            state.current_product_focus = dict(focus)
        return BrainContext(
            tenant_id=1,
            customer_phone="+966500000001",
            message=message,
            intent=intent,
            state=state,
            facts=CommerceFacts(),
            history=[],
            profile={},
        )

    def test_post_catalog_address_does_not_trigger_stash(self):
        from modules.ai.brain.decision.engine import DefaultDecisionEngine
        from modules.ai.brain.decision.actions import ACTION_STASH_ADDRESS_PRE_PRODUCT

        ctx = self._build_ctx(
            focus={
                "id": "catalog_order",
                "external_id": "ext-69",
                "title": "",
                "price": 69.0,
                "currency": "SAR",
                "from_catalog_order": True,
            },
            message="QPMA8668",
            slots={"short_address_code": "QPMA8668"},
        )
        d = DefaultDecisionEngine().decide(ctx)
        assert d.action != ACTION_STASH_ADDRESS_PRE_PRODUCT, (
            "after a catalog order, address signals must flow into the "
            "ordinary order funnel — not back into the pre-product stash"
        )

    def test_pre_catalog_address_still_triggers_stash(self):
        """Belt-and-suspenders: the gate still fires for first-time
        cold customers who genuinely have no product yet."""
        from modules.ai.brain.decision.engine import DefaultDecisionEngine
        from modules.ai.brain.decision.actions import ACTION_STASH_ADDRESS_PRE_PRODUCT

        ctx = self._build_ctx(
            focus=None,
            message="QPMA8668",
            slots={"short_address_code": "QPMA8668"},
        )
        d = DefaultDecisionEngine().decide(ctx)
        assert d.action == ACTION_STASH_ADDRESS_PRE_PRODUCT, (
            "the address-stash gate must still fire when no product has "
            "been chosen and no order funnel is active"
        )


# ── 4. Wire-up sanity ───────────────────────────────────────────────────

class TestPinIsWiredIntoPipeline:
    """Verify by source-grep that ``MerchantBrain.process`` calls
    ``_maybe_pin_catalog_focus`` BEFORE the decision engine. We don't
    import the pipeline module here — heavy imports caused test
    pollution in other suites — so we read the source file directly.
    """

    def test_pipeline_invokes_focus_pin_helper(self):
        src = (REPO_ROOT / "backend" / "modules" / "ai" / "brain" / "pipeline.py").read_text(encoding="utf-8")
        assert "_maybe_pin_catalog_focus(" in src, (
            "MerchantBrain.process must invoke _maybe_pin_catalog_focus"
        )
        # The pin call must precede the decision-engine call so the
        # gate sees the freshly-stamped focus on the same turn.
        idx_pin = src.find("_maybe_pin_catalog_focus(")
        idx_decide = src.find("self._decision_engine.decide(")
        assert 0 < idx_pin < idx_decide, (
            "_maybe_pin_catalog_focus must run before "
            "self._decision_engine.decide(...)"
        )

    def test_marker_constant_matches_normalizer(self):
        """Both modules MUST agree on the catalog-frame marker. If
        the normalizer ever changes its framing string, the pin helper
        would silently stop firing — this guards against that."""
        from modules.ai.media.normalizer import CATALOG_FRAME_MARKER
        from modules.ai.brain.pipeline import _CATALOG_FRAME_MARKER
        assert CATALOG_FRAME_MARKER == _CATALOG_FRAME_MARKER
