"""
tests/test_catalog_focus_pin.py
───────────────────────────────
Locks the surgical-fix contract for **product-focus retention after a
WhatsApp catalog order** (June 2026).

Production reproducer
─────────────────────
The merchant captured a screenshot where a customer:

  1. Submitted a catalog order (a single item, SAR 69).
  2. Was asked for city + address by the bot (correct).
  3. Sent the national-address code and the city name.
  4. Bot then asked: "اختر المنتج اللي تبغاه من القائمة" — wrong, the
     product was already chosen via the catalog order.

Root cause: ``state.current_product_focus`` was never stamped from
the catalog payload, so the decision-engine gate at
``ACTION_STASH_ADDRESS_PRE_PRODUCT`` (which checks
``not state.current_product_focus``) treated the address turn as
"customer hasn't picked a product yet".

What this test file locks
─────────────────────────
1. ``_maybe_pin_catalog_focus`` only fires when the inbound text
   carries the canonical catalog-frame marker generated by
   ``modules.ai.media.normalizer`` — never on plain text.
2. The pin populates ``state.current_product_focus`` with stable
   keys (``id``, ``external_id``, ``title``, ``price``, ``currency``,
   ``from_catalog_order``).
3. When a focus already exists, the helper does **not** overwrite it.
4. Best-effort DB lookup: if the merchant's ``products`` table has
   a row whose ``external_id`` / ``sku`` / ``meta_retailer_id`` matches
   the SKU, the resolved title + numeric id are used. If not, a
   placeholder pin is still applied so the address-stash gate trips.
5. Decision-engine integration: with focus pinned (the post-catalog
   state), an inbound address signal does **not** route to
   ``ACTION_STASH_ADDRESS_PRE_PRODUCT``.
6. The pinning helper is wired into ``MerchantBrain.process`` before
   the decision engine runs (verified by source-grep so we don't
   import the heavy pipeline module at test time).

Constraints this fix obeys
──────────────────────────
* No new intents.
* No new outbound templates / canned replies.
* No new "checkout" layer.
* The brain still chooses the wording — we only flip a state flag
  the decision engine already understood.
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any, List
from unittest.mock import MagicMock

REPO_ROOT = Path(__file__).resolve().parents[1]
for p in [str(REPO_ROOT), str(REPO_ROOT / "backend"), str(REPO_ROOT / "database")]:
    if p not in sys.path:
        sys.path.insert(0, p)


# ── Helpers ──────────────────────────────────────────────────────────────

def _make_catalog_text(
    *,
    sku: str = "ext-69",
    qty: int = 1,
    total: float = 69.0,
    currency: str = "SAR",
    note: str | None = None,
) -> str:
    """Re-create the catalog-frame string the normalizer emits.

    Mirrors ``_process_catalog_order`` in ``modules/ai/media/normalizer.py``;
    we duplicate the shape here intentionally so any unintended drift in
    the marker / fields surfaces as a test failure rather than a silent
    mismatch in production.
    """
    lines: List[str] = ["[طلب كتالوج من العميل]"]
    lines.append(f"عدد المنتجات: {qty}")
    lines.append(f"الإجمالي: {total} {currency}")
    if sku:
        lines.append(f"رمز المنتج (SKU): {sku}")
    if note:
        lines.append(f"ملاحظة من العميل: {note}")
    lines.append("الرجاء معالجة هذا كنية شراء وإكمال الطلب.")
    return "\n".join(lines)


def _make_state(**overrides: Any):
    """Build a fresh ``MerchantConversationState`` with optional overrides."""
    from modules.ai.brain.types import MerchantConversationState
    state = MerchantConversationState()
    for k, v in overrides.items():
        setattr(state, k, v)
    return state


# ── 1. Marker / no-op gating ────────────────────────────────────────────

class TestCatalogFocusPinGating:
    def test_no_marker_does_not_pin(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        state = _make_state()
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1,
            message="السلام عليكم، أبغى عسل",
            state=state,
        )
        assert not state.current_product_focus

    def test_empty_message_does_not_raise(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        state = _make_state()
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1, message="", state=state,
        )
        assert not state.current_product_focus

    def test_none_message_does_not_raise(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        state = _make_state()
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1, message=None, state=state,
        )
        assert not state.current_product_focus

    def test_existing_focus_is_never_overwritten(self):
        """If the customer already picked a product through other paths
        (search → list → pick), the catalog frame must not clobber it."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        existing = {"id": 99, "external_id": "real-99", "title": "عسل سدر فاخر"}
        state = _make_state(current_product_focus=dict(existing))
        msg = _make_catalog_text(sku="other-sku")
        _maybe_pin_catalog_focus(
            db=MagicMock(), tenant_id=1, message=msg, state=state,
        )
        assert state.current_product_focus == existing


# ── 2. Field extraction ─────────────────────────────────────────────────

class TestCatalogFocusPinExtraction:
    def test_pins_with_db_resolution(self):
        """When the SKU matches a product row, prefer its title + id."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        product = MagicMock()
        product.id = 42
        product.title = "عسل سدر مع البروبوليس"
        product.price = 69.0

        # The pipeline calls ``db.query(Product).filter(...).filter(...).first()``.
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = product

        state = _make_state()
        msg = _make_catalog_text(sku="ext-69", qty=1, total=69.0, currency="SAR")
        _maybe_pin_catalog_focus(db=db, tenant_id=7, message=msg, state=state)

        f = state.current_product_focus
        assert f, "expected current_product_focus to be pinned"
        assert f["id"] == 42
        assert f["external_id"] == "ext-69"
        assert f["title"] == "عسل سدر مع البروبوليس"
        assert f["price"] == 69.0
        assert f["currency"] == "SAR"
        assert f["from_catalog_order"] is True

    def test_pins_placeholder_when_sku_unresolved(self):
        """Even when the SKU does not match any product row, we still
        stamp a placeholder focus — that's what gates the
        address-stash branch."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = None

        state = _make_state()
        msg = _make_catalog_text(sku="unknown-sku", qty=1, total=129.0, currency="SAR")
        _maybe_pin_catalog_focus(db=db, tenant_id=7, message=msg, state=state)

        f = state.current_product_focus
        assert f, "placeholder focus must be stamped even when DB lookup misses"
        assert f["external_id"] == "unknown-sku"
        assert f["from_catalog_order"] is True
        # Title falls back to empty so the LLM speaks naturally from
        # context (price / quantity) instead of echoing a fake title.
        assert f["title"] == ""
        assert f["price"] == 129.0
        assert f["currency"] == "SAR"

    def test_pins_when_db_lookup_raises(self):
        """A flaky DB / missing model must not break the pin."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.side_effect = RuntimeError("simulated outage")
        state = _make_state()
        msg = _make_catalog_text(sku="ext-99")
        _maybe_pin_catalog_focus(db=db, tenant_id=1, message=msg, state=state)
        f = state.current_product_focus
        assert f and f["external_id"] == "ext-99"
        assert f["from_catalog_order"] is True

    def test_unit_price_from_total_and_quantity(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = None
        state = _make_state()
        msg = _make_catalog_text(sku="multi", qty=3, total=180.0, currency="SAR")
        _maybe_pin_catalog_focus(db=db, tenant_id=1, message=msg, state=state)
        assert state.current_product_focus["price"] == 60.0  # 180 / 3

    def test_handles_message_with_no_sku(self):
        """Edge case: catalog frame missing SKU line still pins."""
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        db = MagicMock()
        db.query.return_value.filter.return_value.filter.return_value.first.return_value = None
        state = _make_state()
        # Skip the SKU line entirely.
        msg = "[طلب كتالوج من العميل]\nعدد المنتجات: 1\nالإجمالي: 50 SAR\n"
        _maybe_pin_catalog_focus(db=db, tenant_id=1, message=msg, state=state)
        f = state.current_product_focus
        assert f, "focus must still be pinned without an SKU"
        assert f["external_id"] == ""
        assert f["id"] == "catalog_order"
        assert f["from_catalog_order"] is True


# ── 3. Decision-engine integration ──────────────────────────────────────

class TestPostCatalogAddressDoesNotStash:
    """
    With ``current_product_focus`` pinned (the post-catalog state),
    an inbound address signal must NOT route to
    ``ACTION_STASH_ADDRESS_PRE_PRODUCT``.
    """

    def _build_ctx(self, *, focus, message, slots):
        from modules.ai.brain.types import (
            BrainContext,
            CommerceFacts,
            Intent,
            INTENT_GENERAL,
        )
        intent = Intent(
            name=INTENT_GENERAL,
            confidence=0.9,
            raw_message=message,
            slots=dict(slots),
        )
        state = _make_state()
        if focus:
            state.current_product_focus = dict(focus)
        return BrainContext(
            tenant_id=1,
            customer_phone="+966500000001",
            message=message,
            intent=intent,
            state=state,
            facts=CommerceFacts(),
            history=[],
            profile={},
        )

    def test_post_catalog_address_does_not_trigger_stash(self):
        from modules.ai.brain.decision.engine import DefaultDecisionEngine
        from modules.ai.brain.decision.actions import ACTION_STASH_ADDRESS_PRE_PRODUCT

        ctx = self._build_ctx(
            focus={
                "id": "catalog_order",
                "external_id": "ext-69",
                "title": "",
                "price": 69.0,
                "currency": "SAR",
                "from_catalog_order": True,
            },
            message="QPMA8668",
            slots={"short_address_code": "QPMA8668"},
        )
        d = DefaultDecisionEngine().decide(ctx)
        assert d.action != ACTION_STASH_ADDRESS_PRE_PRODUCT, (
            "after a catalog order, address signals must flow into the "
            "ordinary order funnel — not back into the pre-product stash"
        )

    def test_pre_catalog_address_still_triggers_stash(self):
        """Belt-and-suspenders: the gate still fires for first-time
        cold customers who genuinely have no product yet."""
        from modules.ai.brain.decision.engine import DefaultDecisionEngine
        from modules.ai.brain.decision.actions import ACTION_STASH_ADDRESS_PRE_PRODUCT

        ctx = self._build_ctx(
            focus=None,
            message="QPMA8668",
            slots={"short_address_code": "QPMA8668"},
        )
        d = DefaultDecisionEngine().decide(ctx)
        assert d.action == ACTION_STASH_ADDRESS_PRE_PRODUCT, (
            "the address-stash gate must still fire when no product has "
            "been chosen and no order funnel is active"
        )


# ── 4. Wire-up sanity ───────────────────────────────────────────────────

class TestPinIsWiredIntoPipeline:
    """Verify by source-grep that ``MerchantBrain.process`` calls
    ``_maybe_pin_catalog_focus`` BEFORE the decision engine. We don't
    import the pipeline module here — heavy imports caused test
    pollution in other suites — so we read the source file directly.
    """

    def test_pipeline_invokes_focus_pin_helper(self):
        src = (REPO_ROOT / "backend" / "modules" / "ai" / "brain" / "pipeline.py").read_text(encoding="utf-8")
        assert "_maybe_pin_catalog_focus(" in src, (
            "MerchantBrain.process must invoke _maybe_pin_catalog_focus"
        )
        # The pin call must precede the decision-engine call so the
        # gate sees the freshly-stamped focus on the same turn.
        idx_pin = src.find("_maybe_pin_catalog_focus(")
        idx_decide = src.find("self._decision_engine.decide(")
        assert 0 < idx_pin < idx_decide, (
            "_maybe_pin_catalog_focus must run before "
            "self._decision_engine.decide(...)"
        )

    def test_marker_constant_matches_normalizer(self):
        """Both modules MUST agree on the catalog-frame marker. If
        the normalizer ever changes its framing string, the pin helper
        would silently stop firing — this guards against that."""
        from modules.ai.media.normalizer import CATALOG_FRAME_MARKER
        from modules.ai.brain.pipeline import _CATALOG_FRAME_MARKER
        assert CATALOG_FRAME_MARKER == _CATALOG_FRAME_MARKER


# ── 5. Enhanced SKU lookup ladder (June 2026) ────────────────────────────


def _fake_product(*, id_, title, price, external_id="", sku="", meta_retailer_id=""):
    """Stand-in for ``database.models.Product`` so we don't need a
    live DB. Mirrors only the attributes ``_resolve_catalog_product``
    reads."""
    p = MagicMock()
    p.id = id_
    p.title = title
    p.price = price
    p.external_id = external_id or None
    p.sku = sku or None
    p.meta_retailer_id = meta_retailer_id or None
    return p


def _wire_db(*, direct_hit=None, all_rows=None):
    """Build a mock SQLAlchemy session that distinguishes the direct
    chain (``query → filter → filter → first``) from the bulk chain
    (``query → filter → limit → all``).
    """
    db = MagicMock()
    direct_filter = MagicMock()
    direct_filter.filter.return_value.first.return_value = direct_hit
    bulk_chain = MagicMock()
    bulk_chain.limit.return_value.all.return_value = list(all_rows or [])
    # Both chains share ``query().filter()`` — the SAME object then
    # branches into ``.filter(...).first()`` (direct) or
    # ``.limit(...).all()`` (bulk). MagicMock's auto-attribute means
    # both calls reuse the same parent, which works because the
    # direct path uses ``.filter().filter().first()`` and the bulk
    # path uses ``.filter().limit().all()`` — distinct method names.
    parent = MagicMock()
    parent.filter.return_value.first.return_value = direct_hit
    parent.limit.return_value.all.return_value = list(all_rows or [])
    db.query.return_value.filter.return_value = parent
    return db


class TestResolveDirectStrategy:
    def test_direct_hit_short_circuits_bulk_query(self):
        from modules.ai.brain.pipeline import _resolve_catalog_product
        hit = _fake_product(id_=1, title="كريم سم النحل", price=79.0,
                            external_id="ext-79")
        # Pre-populate ALL bulk rows with confounders to prove we
        # short-circuit out of the first pass.
        confounders = [
            _fake_product(id_=2, title="WRONG", price=79.0, external_id="x"),
            _fake_product(id_=3, title="WRONG2", price=79.0, external_id="y"),
        ]
        db = _wire_db(direct_hit=hit, all_rows=confounders)
        row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="ext-79",
            unit_price=79.0, allow_price_fallback=True,
        )
        assert strategy == "direct"
        assert row is hit


class TestResolveNormalizedStrategy:
    def test_hyphen_dropped_id_matches_after_normalization(self):
        """Catalog publishes ``"WA-EXT-101"`` but the row has
        ``external_id="waext101"`` — must still match."""
        from modules.ai.brain.pipeline import _resolve_catalog_product
        row = _fake_product(id_=42, title="كريم سم النحل", price=79.0,
                            external_id="waext101")
        db = _wire_db(direct_hit=None, all_rows=[row])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="WA-EXT-101",
            unit_price=79.0, allow_price_fallback=False,
        )
        assert strategy == "normalized"
        assert out_row is row

    def test_normalized_strategy_compares_against_meta_retailer_id(self):
        from modules.ai.brain.pipeline import _resolve_catalog_product
        row = _fake_product(id_=7, title="منتج", price=10.0,
                            meta_retailer_id="prod_42")
        db = _wire_db(direct_hit=None, all_rows=[row])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="PROD:42",
            unit_price=None, allow_price_fallback=False,
        )
        assert strategy == "normalized"
        assert out_row is row

    def test_normalized_strategy_compares_against_sku(self):
        from modules.ai.brain.pipeline import _resolve_catalog_product
        row = _fake_product(id_=11, title="منتج", price=10.0, sku="abc-123")
        db = _wire_db(direct_hit=None, all_rows=[row])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="ABC123",
            unit_price=None, allow_price_fallback=False,
        )
        assert strategy == "normalized"
        assert out_row is row


class TestResolveUniquePriceStrategy:
    def test_unique_price_match_returns_row(self):
        """When SKU misses entirely AND no payload name was supplied,
        a single tenant product at the matching price wins."""
        from modules.ai.brain.pipeline import _resolve_catalog_product
        row = _fake_product(id_=99, title="كريم سم النحل", price="79.0",
                            external_id="ext-NEHEL")
        confounder = _fake_product(id_=100, title="عسل", price="120.0",
                                   external_id="ext-honey")
        db = _wire_db(direct_hit=None, all_rows=[row, confounder])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="totally-unknown",
            unit_price=79.0, allow_price_fallback=True,
        )
        assert strategy == "unique_price"
        assert out_row is row

    def test_two_products_with_same_price_refuse_to_guess(self):
        """If multiple products share the price, the resolver must
        return ``"miss"`` rather than silently picking the first."""
        from modules.ai.brain.pipeline import _resolve_catalog_product
        a = _fake_product(id_=1, title="A", price="79.0", external_id="a")
        b = _fake_product(id_=2, title="B", price="79.0", external_id="b")
        db = _wire_db(direct_hit=None, all_rows=[a, b])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="unknown",
            unit_price=79.0, allow_price_fallback=True,
        )
        assert strategy == "miss"
        assert out_row is None

    def test_price_fallback_disabled_when_payload_name_present(self):
        """Caller controls the fallback toggle. When WhatsApp already
        gave us a name we never want to second-guess it via price."""
        from modules.ai.brain.pipeline import _resolve_catalog_product
        row = _fake_product(id_=99, title="some other product", price="79.0",
                            external_id="ext")
        db = _wire_db(direct_hit=None, all_rows=[row])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="unknown",
            unit_price=79.0, allow_price_fallback=False,
        )
        assert strategy == "miss"
        assert out_row is None

    def test_price_fallback_skipped_when_unit_price_unknown(self):
        from modules.ai.brain.pipeline import _resolve_catalog_product
        row = _fake_product(id_=99, title="X", price="79.0", external_id="ext")
        db = _wire_db(direct_hit=None, all_rows=[row])
        out_row, strategy = _resolve_catalog_product(
            db=db, tenant_id=1, sku="",
            unit_price=None, allow_price_fallback=True,
        )
        assert strategy == "miss"
        assert out_row is None


class TestResolveLogsAndDiagnostics:
    def test_focus_log_includes_db_lookup_matched_and_strategy(self, caplog):
        """``[CATALOG_FOCUS]`` line must surface the two diagnostic
        fields the merchant asked for so a log grep instantly answers
        'did we find the row, and how?'."""
        import logging as _lg
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        from modules.ai.brain.types import MerchantConversationState

        hit = _fake_product(id_=1, title="كريم سم النحل", price=79.0,
                            external_id="ext-79")
        db = _wire_db(direct_hit=hit, all_rows=[])

        msg = "\n".join([
            "[طلب كتالوج من العميل]",
            "عدد المنتجات: 1",
            "الإجمالي: 79 SAR",
            "رمز المنتج (SKU): ext-79",
        ])
        state = MerchantConversationState()
        with caplog.at_level(_lg.INFO, logger="nahla.brain.pipeline"):
            _maybe_pin_catalog_focus(
                db=db, tenant_id=42, message=msg, state=state,
            )
        focus_lines = [
            r.getMessage() for r in caplog.records
            if "[CATALOG_FOCUS]" in r.getMessage()
        ]
        assert focus_lines, "no [CATALOG_FOCUS] log line emitted"
        line = focus_lines[-1]
        assert "db_lookup_matched=True" in line
        assert "match_strategy=direct" in line
        assert "tenant=42" in line

    def test_focus_log_records_miss_strategy(self, caplog):
        import logging as _lg
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        from modules.ai.brain.types import MerchantConversationState

        db = _wire_db(direct_hit=None, all_rows=[])
        msg = "\n".join([
            "[طلب كتالوج من العميل]",
            "عدد المنتجات: 1",
            "الإجمالي: 79 SAR",
            "رمز المنتج (SKU): unknown",
        ])
        state = MerchantConversationState()
        with caplog.at_level(_lg.INFO, logger="nahla.brain.pipeline"):
            _maybe_pin_catalog_focus(
                db=db, tenant_id=1, message=msg, state=state,
            )
        line = next(
            r.getMessage() for r in caplog.records
            if "[CATALOG_FOCUS]" in r.getMessage()
        )
        assert "db_lookup_matched=False" in line
        assert "match_strategy=miss" in line


class TestPinIntegrationWithEnhancedLookup:
    """End-to-end checks at the ``_maybe_pin_catalog_focus`` boundary —
    the resolver wiring must surface the right title."""

    def test_pin_picks_unique_price_match_when_sku_unknown(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        from modules.ai.brain.types import MerchantConversationState

        # The screenshot scenario: WhatsApp gave us a SKU we don't
        # know, no payload name, but the merchant has exactly ONE
        # product at 79 SAR — "كريم سم النحل".
        unique = _fake_product(id_=33, title="كريم سم النحل",
                               price="79.0", external_id="real-id")
        db = _wire_db(direct_hit=None, all_rows=[unique])
        msg = "\n".join([
            "[طلب كتالوج من العميل]",
            "عدد المنتجات: 1",
            "الإجمالي: 79 SAR",
            "رمز المنتج (SKU): bsp-divergent-id",
        ])
        state = MerchantConversationState()
        _maybe_pin_catalog_focus(
            db=db, tenant_id=1, message=msg, state=state,
        )
        f = state.current_product_focus
        assert f, "focus must be pinned"
        assert f["title"] == "كريم سم النحل"
        assert f["id"] == 33
        assert f["from_catalog_order"] is True

    def test_pin_does_not_use_price_fallback_when_payload_name_exists(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        from modules.ai.brain.types import MerchantConversationState

        # Same price collision but payload name was supplied — must
        # respect the BSP-supplied label, never override via price.
        row = _fake_product(id_=99, title="DO NOT USE", price="79.0",
                            external_id="x")
        db = _wire_db(direct_hit=None, all_rows=[row])
        msg = "\n".join([
            "[طلب كتالوج من العميل]",
            "عدد المنتجات: 1",
            "الإجمالي: 79 SAR",
            "اسم المنتج: كريم سم النحل",
            "رمز المنتج (SKU): bsp-divergent-id",
        ])
        state = MerchantConversationState()
        _maybe_pin_catalog_focus(
            db=db, tenant_id=1, message=msg, state=state,
        )
        # Title comes from the payload, NOT the unique-price product.
        assert state.current_product_focus["title"] == "كريم سم النحل"

    def test_pin_uses_normalized_match_for_hyphen_drift(self):
        from modules.ai.brain.pipeline import _maybe_pin_catalog_focus
        from modules.ai.brain.types import MerchantConversationState

        row = _fake_product(id_=44, title="كريم سم النحل",
                            price="79.0", external_id="waext101")
        db = _wire_db(direct_hit=None, all_rows=[row])
        msg = "\n".join([
            "[طلب كتالوج من العميل]",
            "عدد المنتجات: 1",
            "الإجمالي: 79 SAR",
            "رمز المنتج (SKU): WA-EXT-101",
        ])
        state = MerchantConversationState()
        _maybe_pin_catalog_focus(
            db=db, tenant_id=1, message=msg, state=state,
        )
        assert state.current_product_focus["title"] == "كريم سم النحل"
        assert state.current_product_focus["id"] == 44


class TestSkuTokenNormalization:
    def test_strips_punctuation_and_lowercases(self):
        from modules.ai.brain.pipeline import _normalize_sku_token
        assert _normalize_sku_token("WA-EXT-101")    == "waext101"
        assert _normalize_sku_token("  Wa Ext 101  ") == "waext101"
        assert _normalize_sku_token("wa:ext:101")    == "waext101"
        assert _normalize_sku_token("waext101")      == "waext101"

    def test_handles_empty_or_none(self):
        from modules.ai.brain.pipeline import _normalize_sku_token
        assert _normalize_sku_token("")   == ""
        assert _normalize_sku_token(None) == ""
