#!/usr/bin/env python3
"""Bundle the read-only catalog trial readout into one self-contained file.

``backend/services/catalog_trial_readout.py`` only exists on the feature
branch, while the readout must run against the *deployed* code version
before merge. This script writes
``scripts/operators/catalog_trial_readout_standalone.py``: the service module
verbatim plus a CLI, so the operator can ship a single file into the running
container (``railway ssh``) without replacing any application file.

Regenerate after editing the service module::

    python scripts/operators/build_catalog_trial_readout_standalone.py

``tests/test_catalog_trial_readout.py`` fails when the bundled copy
drifts from the service module.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SERVICE = ROOT / "backend" / "services" / "catalog_trial_readout.py"
TARGET = ROOT / "scripts" / "operators" / "catalog_trial_readout_standalone.py"

BEGIN = "# ── BEGIN bundled backend/services/catalog_trial_readout.py ──"
END = "# ── END bundled backend/services/catalog_trial_readout.py ──"

HEADER = '''#!/usr/bin/env python3
"""Standalone, read-only WhatsApp-catalog trial readout (generated file).

Generated by scripts/operators/build_catalog_trial_readout_standalone.py from
backend/services/catalog_trial_readout.py — do not edit by hand.

Runs inside the deployed service container, against the code version that is
live there (it needs only modules that exist on ``main``), with that
environment's own DATABASE_URL and WhatsApp token. It never writes to the
database, never POSTs to Meta, and never prints a token.

Typical use from an operator machine with the Railway CLI logged in::

    # prints the one-line railway ssh command that carries this file (base64)
    python scripts/operators/catalog_trial_readout_standalone.py \\
        --print-ssh-command --tenant-id 35 --include-graph

    # or, inside an interactive `railway ssh` session, after pasting the file to /tmp:
    cd /app && python /tmp/catalog_trial_readout_standalone.py --tenant-id 35 --include-graph --pretty
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve()


def _bootstrap_sys_path() -> None:
    """Make ``services``, ``core``, ``models`` importable from /app or a checkout."""
    candidates = [Path("/app"), Path.cwd()]
    for parent in (_HERE.parent, *_HERE.parents):
        candidates.append(parent)
    for root in candidates:
        if (root / "backend" / "services").is_dir() and (root / "database" / "models.py").is_file():
            for p in (root, root / "backend", root / "database"):
                if str(p) not in sys.path:
                    sys.path.insert(0, str(p))
            return


_bootstrap_sys_path()

'''

FOOTER = '''

def _ssh_command(args: argparse.Namespace) -> str:
    payload = base64.b64encode(_HERE.read_bytes()).decode("ascii")
    flags = f"--tenant-id {int(args.tenant_id)}"
    if args.include_graph:
        flags += " --include-graph"
    if args.include_salla:
        flags += " --include-salla"
    if args.candidate_ids:
        flags += f" --candidate-ids {args.candidate_ids}"
    if args.expected_business_id:
        flags += f" --expected-business-id {args.expected_business_id}"
    flags += f" --candidates {int(args.candidates)} --pretty"
    remote = (
        "bash -lc 'echo " + payload + " | base64 -d > /tmp/catalog_trial_readout_standalone.py "
        "&& cd /app && python /tmp/catalog_trial_readout_standalone.py " + flags + "'"
    )
    return (
        f"railway ssh --environment {args.railway_environment} --service {args.railway_service} -- {remote}"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Read-only WhatsApp catalog trial readout for one tenant (no secrets in output).",
    )
    parser.add_argument("--tenant-id", type=int, required=True)
    parser.add_argument("--include-graph", action="store_true", help="Also read Meta Graph (GET only).")
    parser.add_argument("--candidates", type=int, default=3)
    parser.add_argument("--candidate-ids", default="", help="Comma-separated local product ids chosen by the owner.")
    parser.add_argument("--expected-business-id", default="", help="Business Manager id expected to own the WABA and its catalog.")
    parser.add_argument("--include-salla", action="store_true", help="Re-read anomalous products from Salla (GET only, stored token as is: never refreshed or saved; refused when expired or rejected).")
    parser.add_argument("--pretty", action="store_true")
    parser.add_argument("--print-ssh-command", action="store_true",
                        help="Print the railway ssh one-liner that ships this file and runs it; do nothing else.")
    parser.add_argument("--railway-service", default="nahla-saas")
    parser.add_argument("--railway-environment", default="production")
    args = parser.parse_args()

    if args.print_ssh_command:
        print(_ssh_command(args))
        return 0

    db_url = os.environ.get("DATABASE_URL")
    if not db_url:
        print("DATABASE_URL is not set in this environment", file=sys.stderr)
        return 1
    from sqlalchemy import create_engine  # noqa: PLC0415
    from sqlalchemy.orm import sessionmaker  # noqa: PLC0415

    import models  # noqa: F401,PLC0415  (registers the ORM tables on Base)

    engine = create_engine(db_url)
    db = sessionmaker(bind=engine)()
    try:
        report = build_catalog_trial_readout(
            db, int(args.tenant_id), include_graph=bool(args.include_graph), candidate_count=int(args.candidates),
            candidate_ids=[int(x) for x in args.candidate_ids.replace(";", ",").split(",") if x.strip().isdigit()] or None,
            expected_business_id=args.expected_business_id or None,
            include_salla=bool(args.include_salla),
        )
        db.rollback()
        print(json.dumps(report, ensure_ascii=False, indent=2 if args.pretty else None, default=str))
        print(
            "trial-readout tenant=%s products=%s eligible=%s missing=%s"
            % (
                report["tenant_id"],
                report["product_counts"]["total"],
                report["product_counts"]["publish_eligible"],
                ",".join(report["missing_requirements"]) or "none",
            ),
            file=sys.stderr,
        )
        return 0 if report["tenant"]["exists"] else 2
    finally:
        db.close()
        engine.dispose()


if __name__ == "__main__":
    raise SystemExit(main())
'''


def build() -> str:
    body = SERVICE.read_text(encoding="utf-8")
    # the service module's own `from __future__` must not appear mid-file
    body = body.replace("from __future__ import annotations\n", "", 1)
    return HEADER + BEGIN + "\n" + body.rstrip("\n") + "\n" + END + FOOTER


def main() -> int:
    TARGET.write_text(build(), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({TARGET.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
