"""Add taxonomy columns to coupons: source_type, coupon_level, allocation_channel.

Revision ID: 0038
Revises: 0037

Background
──────────
Until now coupons carried their classification only inside the JSONB
``metadata.source`` field, which left the dashboard guessing whether
a code was generated by the system, imported from Salla, or created
manually by the merchant. The classifier in ``routers/coupons.py`` was
also out of sync with the writer in ``services/coupon_generator.py``
(``"auto"`` vs ``"automation"``), so every system-generated coupon
displayed as "يدوي".

This migration promotes that classification to first-class columns and
backfills existing rows so the dashboard renders correct origin/level/
channel chips immediately after deploy.

Columns
───────
* ``source_type``         — manual | system | imported  (default 'manual')
* ``coupon_level``        — bronze | silver | gold | vip   (nullable)
* ``allocation_channel``  — ai | campaign | autopilot | shared (nullable)
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = "0038"
down_revision = "0037"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "coupons",
        sa.Column(
            "source_type",
            sa.String(),
            nullable=False,
            server_default=sa.text("'manual'"),
        ),
    )
    op.add_column("coupons", sa.Column("coupon_level", sa.String(), nullable=True))
    op.add_column("coupons", sa.Column("allocation_channel", sa.String(), nullable=True))

    op.create_index("ix_coupons_source_type", "coupons", ["source_type"])
    op.create_index("ix_coupons_coupon_level", "coupons", ["coupon_level"])

    # ── Backfill from extra_metadata.source ──────────────────────────────
    # Auto-pool rows write source='auto'; promotion materialiser writes
    # 'promotion'; on-demand AI writes 'auto' too. Map them all to 'system'
    # so the dashboard collapses the implementation detail into a single
    # merchant-facing bucket.
    op.execute("""
        UPDATE coupons
           SET source_type = 'system'
         WHERE LOWER(COALESCE(metadata->>'source', '')) IN
               ('auto', 'auto_generated', 'system', 'pool', 'automation', 'promotion')
            OR (metadata->>'auto_generated')::text = 'true'
    """)
    op.execute("""
        UPDATE coupons
           SET source_type = 'imported'
         WHERE LOWER(COALESCE(metadata->>'source', '')) IN
               ('salla', 'zid', 'imported')
            OR (metadata->>'salla_synced')::text = 'true'
            AND source_type = 'manual'
    """)

    # ── Backfill coupon_level from segment / VIP flag ────────────────────
    op.execute("""
        UPDATE coupons
           SET coupon_level = CASE
               WHEN LOWER(COALESCE(metadata->>'target_segment', '')) IN ('vip','at_risk') THEN 'vip'
               WHEN LOWER(COALESCE(metadata->>'target_segment', '')) = 'gold' THEN 'gold'
               WHEN LOWER(COALESCE(metadata->>'target_segment', '')) IN ('active','silver') THEN 'silver'
               WHEN LOWER(COALESCE(metadata->>'target_segment', '')) IN ('new','bronze','lead') THEN 'bronze'
               WHEN (metadata->>'vip')::text = 'true' THEN 'vip'
               ELSE NULL
           END
         WHERE coupon_level IS NULL
    """)

    # ── Backfill allocation_channel ──────────────────────────────────────
    op.execute("""
        UPDATE coupons
           SET allocation_channel = CASE
               WHEN metadata->>'campaign_id' IS NOT NULL THEN 'campaign'
               WHEN LOWER(COALESCE(metadata->>'source', '')) IN ('automation','auto') THEN 'autopilot'
               WHEN LOWER(COALESCE(metadata->>'source', '')) = 'promotion' THEN 'shared'
               WHEN LOWER(COALESCE(metadata->>'channel', '')) IN ('ai','chat','brain') THEN 'ai'
               ELSE NULL
           END
         WHERE allocation_channel IS NULL
    """)

    op.alter_column("coupons", "source_type", server_default=None)


def downgrade() -> None:
    op.drop_index("ix_coupons_coupon_level", table_name="coupons")
    op.drop_index("ix_coupons_source_type", table_name="coupons")
    op.drop_column("coupons", "allocation_channel")
    op.drop_column("coupons", "coupon_level")
    op.drop_column("coupons", "source_type")
